list = input("Введите первый список слов через запятую: ")
list = list.split(",")
list_copy = set(list)
count_words = len(list)
print("В списке {} слов".format(count_words))
list2 = input("Введите второй список из {} слов через запятую: ".format(count_words))
list2 = list2.split(",")
list_copy2 = set(list2)
slovar = dict(zip(list, list2))
print(slovar)
